In [17]:
import numpy as np
import pandas as pd  
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
all_data = pd.read_csv('all_data.csv')

In [19]:
all_data.head()

,Rk,Name,YoB,Votes,%vote,HOFm,HOFs,Yrs,WAR,WAR7,...,WHIP,G.1,GS,SV,IP,H.1,HR.1,BB.1,SO,Pos Summary
0,1,Ted Williams,1st,282,93.4%,354,73,19,121.8,67.9,...,1.500,1.0,0.0,0.0,2.0,3.0,0.0,0.0,1.0,*79H/1
1,2,Red Ruffing HOF,14th,208,68.9%,130,38,22,68.7,39.9,...,1.341,624.0,538.0,18.0,4344.0,4284.0,254.0,1541.0,1987.0,*1H/79
2,3,Roy Campanella HOF,2nd,197,65.2%,146,43,18,42.0,35.0,...,1.239,2.0,2.0,0.0,15.1,13.0,1.0,6.0,16.0,*2H/97815
3,4,Joe Medwick HOF,7th,187,61.9%,200,47,17,54.4,39.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*7H9/38
4,5,Lou Boudreau HOF,6th,115,38.1%,89,34,15,63.2,48.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*65H/342

Remove all players whose primary position was pitcher (indicated by *1 in the position summary column).

In [20]:
all_data_clean = all_data[~all_data['Pos\xa0Summary'].str.contains('*1', regex = False)]

In [21]:
all_data_clean.head()

,Rk,Name,YoB,Votes,%vote,HOFm,HOFs,Yrs,WAR,WAR7,...,WHIP,G.1,GS,SV,IP,H.1,HR.1,BB.1,SO,Pos Summary
0,1,Ted Williams,1st,282,93.4%,354,73,19,121.8,67.9,...,1.500,1.0,0.0,0.0,2.0,3.0,0.0,0.0,1.0,*79H/1
2,3,Roy Campanella HOF,2nd,197,65.2%,146,43,18,42.0,35.0,...,1.239,2.0,2.0,0.0,15.1,13.0,1.0,6.0,16.0,*2H/97815
3,4,Joe Medwick HOF,7th,187,61.9%,200,47,17,54.4,39.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*7H9/38
4,5,Lou Boudreau HOF,6th,115,38.1%,89,34,15,63.2,48.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*65H/342
5,6,Al Lopez HOF,9th,109,36.1%,71,24,19,16.4,11.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*2H/453

In [22]:
all_data_clean.columns

Index(['Rk', 'Name', 'YoB', 'Votes', '%vote', 'HOFm', 'HOFs', 'Yrs', 'WAR',
       'WAR7', 'JAWS', 'Jpos', 'G', 'AB', 'R', 'H', 'HR', 'RBI', 'SB', 'BB',
       'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'W', 'L', 'ERA', 'ERA+', 'WHIP',
       'G.1', 'GS', 'SV', 'IP', 'H.1', 'HR.1', 'BB.1', 'SO', 'Pos Summary'],
      dtype='object')

Now we want to drop all the columns that have to do with pitching stats.

In [23]:
all_data_clean = all_data_clean.drop(['W','L','ERA','ERA+','WHIP','G.1','GS','SV','IP','H.1','HR.1','BB.1','SO'], axis = 1)

In [24]:
all_data_clean.head()

,Rk,Name,YoB,Votes,%vote,HOFm,HOFs,Yrs,WAR,WAR7,...,HR,RBI,SB,BB,BA,OBP,SLG,OPS,OPS+,Pos Summary
0,1,Ted Williams,1st,282,93.4%,354,73,19,121.8,67.9,...,521,1839,24,2021,0.344,0.482,0.634,1.116,191.0,*79H/1
2,3,Roy Campanella HOF,2nd,197,65.2%,146,43,18,42.0,35.0,...,260,1019,38,609,0.283,0.363,0.496,0.859,125.0,*2H/97815
3,4,Joe Medwick HOF,7th,187,61.9%,200,47,17,54.4,39.2,...,205,1383,42,437,0.324,0.362,0.505,0.867,134.0,*7H9/38
4,5,Lou Boudreau HOF,6th,115,38.1%,89,34,15,63.2,48.9,...,68,789,51,796,0.295,0.380,0.415,0.795,120.0,*65H/342
5,6,Al Lopez HOF,9th,109,36.1%,71,24,19,16.4,11.2,...,51,652,46,556,0.261,0.326,0.337,0.663,83.0,*2H/453

In [25]:
all_data_clean.columns

Index(['Rk', 'Name', 'YoB', 'Votes', '%vote', 'HOFm', 'HOFs', 'Yrs', 'WAR',
       'WAR7', 'JAWS', 'Jpos', 'G', 'AB', 'R', 'H', 'HR', 'RBI', 'SB', 'BB',
       'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'Pos Summary'],
      dtype='object')

Now we want to drop the irrelevant columns Rk, Name, Pos Summary (it would be interesting to try to incorporate position but we'll leave that for another time as the Pos Summary columns would require some cleaning), and Votes (as we really care about %vote).

In [26]:
all_data_clean = all_data_clean.drop(['Rk','Name','Pos\xa0Summary', 'Votes'], axis = 1)

In [27]:
all_data_clean

,YoB,%vote,HOFm,HOFs,Yrs,WAR,WAR7,JAWS,Jpos,G,...,H,HR,RBI,SB,BB,BA,OBP,SLG,OPS,OPS+
0,1st,93.4%,354,73,19,121.8,67.9,94.9,53.4,2292,...,2654,521,1839,24,2021,0.344,0.482,0.634,1.116,191.0
2,2nd,65.2%,146,43,18,42.0,35.0,38.5,44.2,1449,...,1422,260,1019,38,609,0.283,0.363,0.496,0.859,125.0
3,7th,61.9%,200,47,17,54.4,39.2,46.8,53.4,1984,...,2471,205,1383,42,437,0.324,0.362,0.505,0.867,134.0
4,6th,38.1%,89,34,15,63.2,48.9,56.0,55.4,1646,...,1779,68,789,51,796,0.295,0.380,0.415,0.795,120.0
5,9th,36.1%,71,24,19,16.4,11.2,13.8,44.2,1950,...,1547,51,652,46,556,0.261,0.326,0.337,0.663,83.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2078,1st,1.5%,109,33,14,50.6,38.0,44.3,53.4,1862,...,1862,409,1298,26,918,0.268,0.360,0.509,0.869,126.0
2080,1st,1.3%,56,20,14,27.0,24.4,25.7,53.4,1545,...,1603,247,985,5,573,0.281,0.348,0.481,0.828,120.0
2081,1st,0.5%,108,30,19,23.8,18.1,20.9,44.2,2059,...,2043,188,909,15,308,0.280,0.319,0.420,0.739,94.0
2082,1st,0.5%,85,27,12,23.8,24.9,24.4,53.4,1611,...,1645,319,1028,18,847,0.283,0.382,0.506,0.887,134.0
2084,1st,0.0%,53,22,15,39.1,32.3,35.7,53.4,1716,...,1931,136,766,480,377,0.290,0.330,0.435,0.765,105.0

Replace %vote with a decimal, and YoB ordinal with an integer.

In [28]:
all_data_clean['%vote'] = all_data_clean['%vote'].str.replace('%', '').astype(float) / 100
all_data_clean['YoB'] = all_data_clean['YoB'].str.replace(r'\D', '', regex=True).astype(int)

In [29]:
all_data_clean

,YoB,%vote,HOFm,HOFs,Yrs,WAR,WAR7,JAWS,Jpos,G,...,H,HR,RBI,SB,BB,BA,OBP,SLG,OPS,OPS+
0,1,0.934,354,73,19,121.8,67.9,94.9,53.4,2292,...,2654,521,1839,24,2021,0.344,0.482,0.634,1.116,191.0
2,2,0.652,146,43,18,42.0,35.0,38.5,44.2,1449,...,1422,260,1019,38,609,0.283,0.363,0.496,0.859,125.0
3,7,0.619,200,47,17,54.4,39.2,46.8,53.4,1984,...,2471,205,1383,42,437,0.324,0.362,0.505,0.867,134.0
4,6,0.381,89,34,15,63.2,48.9,56.0,55.4,1646,...,1779,68,789,51,796,0.295,0.380,0.415,0.795,120.0
5,9,0.361,71,24,19,16.4,11.2,13.8,44.2,1950,...,1547,51,652,46,556,0.261,0.326,0.337,0.663,83.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2078,1,0.015,109,33,14,50.6,38.0,44.3,53.4,1862,...,1862,409,1298,26,918,0.268,0.360,0.509,0.869,126.0
2080,1,0.013,56,20,14,27.0,24.4,25.7,53.4,1545,...,1603,247,985,5,573,0.281,0.348,0.481,0.828,120.0
2081,1,0.005,108,30,19,23.8,18.1,20.9,44.2,2059,...,2043,188,909,15,308,0.280,0.319,0.420,0.739,94.0
2082,1,0.005,85,27,12,23.8,24.9,24.4,53.4,1611,...,1645,319,1028,18,847,0.283,0.382,0.506,0.887,134.0
2084,1,0.000,53,22,15,39.1,32.3,35.7,53.4,1716,...,1931,136,766,480,377,0.290,0.330,0.435,0.765,105.0

And export our results.

In [30]:
all_data_clean.to_csv('all_data_clean.csv', index = False)